### ISSUE TITLE
Panorama's are moving in the wrong direction

### ISSUE THREAD

**Issue by Capotea** [fmos/wp-photonav#1]
Hi,

I noticed today that my panorama's are moving in the wrong direction and are not shown in total.
When clicking on the panorama it opens in the lightbox, but I cannot scroll through it as I usually could.

An example is here: http://blog.fokkio.nl/oostvaardersplassen-ingang-almere/

It used to work good.

Can you help me with this problem?

Thanks in advance.

**Comment by fmos** [comment]
Hi, thank you for reporting this problem and providing the link!

I visited the site you pointed me to and tried to identify the problem, but couldn't find out what's going wrong. I'm pretty sure it has something to do with the theme, as it's also intercepting right-clicks (you can't right-click on an image and save it) for instance, which probably breaks the `drag` mode in some way.

If you can not switch the theme of your blog, please try using the default `move` mode of photonav (by chainging the respective option in the shortcode) and see if at least that works.

**Comment by danikaze** [comment]
I'm having the same issue.
http://blog.danielberlanga.es/panoramica-desde-mi-azotea-actual/comment-page-1/#

sometimes works ok, sometimes it moves in the opposite direction leaving a blank space, but when you move the mouse over the image works fine.

**Comment by fmos** [comment]
This should be solved by release 1.0.2.
