### ISSUE TITLE
Add new behavior on the "Move" mode

### ISSUE THREAD

**Issue by orensbruli** [fmos/wp-photonav#15]
Hi,
I have added a new behavior to the "Move" mode. You can see it here:
http://emartinena.es/galerias/panoramicas
The idea is to see the full photo while mouse is out of the container and to get a zoom and move on hover.
I have tried to create a branch and to upload it but github says that I "may not have permission to access wp-photonav".
Can U help me?
Thank U in advance.
Greetings.

**Comment by fmos** [comment]
Hi,

I think this is a good idea also to display the full image for mobile devices (without a mouse), where the navigation is inaccessible. One thing I noticed though is that some images change in size significantly between "full view" and "zoom view". Is this due to the different proportions of the images or is there a different reason?

To upload your code to GitHub, you need to create a branch in your own repository, i.e. under your own nickname and push your code there. Then I can review your changes and merge them into my branch as soon as the feature is stable and working.

Cheers.

**Comment by orensbruli** [comment]
Hi,

I think that the reason of the different sizes between the full view and the zoom is that I have set the size of the container as parameter of  the shortcode with container_height=300. Could it be? I don't dislike that behaviour, do you? Anyway I can take a look to that.

I have created a brach of your project. But I can't upload/publish it. It say I have no permissions to do it. Does I need to be a contributor (or something) to do that?
The other way I see to upload is to create a fork of the project and them create a branch, but in this way I don't know if you could integrate the changes easily.

**Comment by fmos** [comment]
Hi,

I think creating a "fork" is exactly the right way. As far as I understand, a fork is nothing else than a branch to which you can push, i.e. exactly what you want. Then I will be able to access your branch and review/merge your changes.

**Comment by orensbruli** [comment]
Sorry, I had no previous experience with git. I did what you suggested and I uploaded the changes. You can see it here:
https://github.com/orensbruli/wp-photonav/compare/master...Full-View
Thank U again.

**Comment by orensbruli** [comment]
Hi,
Did you had time to review my "fork"?

Thank U.

**Comment by fmos** [comment]
Finally I had time to review and play with your changes. I developed them a bit further to make the full view follow resizes of the window automatically. It would be great if you could test my code (not released, only committed here) at some point.

**Comment by orensbruli** [comment]
Hi Fabian,

Thank u so much for reviewing my code.
I just found a problem: when the mouse come out of the frame the image
does't return to it original size/zoom.
Let me know If I can help in anything else.
Greetings.

On 30 June 2014 23:35, Fabian Stanke notifications@github.com wrote:

> Finally I had time to review and play with your changes. I developed them
> a bit further to make the full view follow resizes of the window
> automatically. It would be great if you could test my code (not released,
> only committed here) at some point.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/fmos/wp-photonav/issues/15#issuecomment-47590395.

## 

Esteban Martinena Guerrero
Fotografía de autor y de prensa
Colaborador Agencia EFE
_Facebook_: https://www.facebook.com/EMartinenaPhoto
_Website_: http://emartinena.es
http://www.copiaoculta.com

**Comment by fmos** [comment]
Hi Esteban,
Thank you for your quick feedback! I have just committed a refined implementation (now the zooming is treated as an animation, i.e. by setting animate=zoom). This version (8f5178f) has worked fine during my tests, but I have not yet released it on wordpress.org to clarify this issue. It would be great, if you could check if the problem you reported persists with this version and if so, report which mode (move, drag,...) you are using and which image dimensions etc.
Greetings!
