### ISSUE TITLE
speed variation

### ISSUE THREAD

**Issue by niouje** [fmos/wp-photonav#20]
hi fmos!
Your plugin is very good for me who create an infinite horizontal slideshow. I just have a question : how can i change the speed of the scrolling? 
perhaps it will be a good thing to add this parameters in the shortcode?

Thx and sorry fo my bad english : i'm just french ;)

**Comment by fmos** [comment]
Hi, thank you for your feedback. Currently the speed is fixed. Another parameter shouldn't be too difficult to implement. I'll see what I can do ... ;)

**Comment by niouje** [comment]
ok no problem. i have some knowledge in php so i'll try to find how i can change the speed :)
