### ISSUE TITLE
Marker or label for panoramas

### ISSUE THREAD

**Issue by fmos** [fmos/wp-photonav#3]
It would be nice to recognize that panorama pictures are "different", i.e. that they can be interacted with, which is not clear when using drag mode.
Some Label "drag me" that disappears upon interaction would be a solution.

**Comment by danikaze** [comment]
I did it by javascript and css, so there's no need to add it in the plugin to preserver it simple, I think.
You can check how I did it in my blog if you want. The css and js is easily visible.
http://blog.danielberlanga.es/kabukicho-de-noche/
