### ISSUE TITLE
JavaScript object TypeError

### ISSUE THREAD

**Issue by fmos** [fmos/wp-photonav#4]
> Reported by Daniel Berlanga (Danikaze) on the plugin page]

I’m getting this in the javascript console…

```
Uncaught TypeError: Object [object Object] has no method 'photoNav'
```

using Chrome on Win7 x64

**Comment by fmos** [comment]
I can not reproduce this on Chrome Win8 x64. I'm having the JavaScript console open, but nothing is displayed and the panoramas work fine.
Can you tell me, which theme you're using?

**Comment by danikaze** [comment]
I'm using a custom theme from scratch...
Is there any prerequisite I should add to make it work?

I added the following code
`[photonav url='/wp-content/uploads/2013/01/MG_4097-Editar.jpg' mode='move' popup='none' container_width=900 container_height=600]`

to this page http://blog.danielberlanga.es/acerca-de/ so you can test it (before the Spanish text in the main entry)

Updated the plugin but still getting this
`Uncaught TypeError: Object [object Object] has no method 'photoNav'`

in this line of code
`<script type="text/javascript">jQuery(document).ready(function(){jQuery("#c240cf87d38246ff").photoNav({id:"c240cf87d38246ff",mode:"move",popup:"none",animate:"0"});});</script>`

Still using Win7 x64 with WordPress 3.5.1
Tested on Chrome, IE and FF, always the same result

**Comment by fmos** [comment]
On your page I can see the problem.

There is no prerequisite you should add, but rather remove something: Looking at your page's source this is what I understand is happening (only the relevant steps) in this order:
- WordPress loads jQuery (version 1.8.3) on line 45 of the html
- WP-PhotoNav (which is a jQuery plugin) registers with the loaded jQuery on line 51
- A different version of jQuery (version 1.6.4) is loaded on line 91, overwriting the previous jQuery and of course the plugins registered there.

I assume, the last step is part of your theme?! Is there a reason you need an old version of jQuery? If not, you should really work with the version of jQuery coming with WordPress and you should not load it "manually", but by calling `wp_enqueue_script('jquery');` from your theme (see the [WordPress API](http://codex.wordpress.org/Function_Reference/wp_enqueue_script) for more info). This will ensure the correct load sequence when loading plugins.

**Comment by danikaze** [comment]
Thank you!
Didn't know about that. Now it works perfectly.

Thanks again!

http://danielberlanga.es

2013/3/7 Fabian Stanke notifications@github.com

**Comment by danikaze** [comment]
My fault! It Works now!

**Comment by fmos** [comment]
Fine. I'm glad I could help.
